spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/couzy_forum?serverTimezone=UTC&useSSL=false"
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      show-sql: true
      hbm2ddl:
        auto: create-drop
    profiles:
      active: dev
    show-sql: ${SHOW_SQL:true}  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: some
            client-secret: some-secret
            scope: user::email, read::user
          google:
            client-id: some
            client-secret: some-secret
            scope: email, profile
          facebook:
            client-id: some
            client-secret: some-secret
            scope: email, public_profile
  # Kafka
  kafka:
    security:
      protocol: SSL
    comsumer:
      bootstrap-servers: my-broker1.com:9094,my-broker2.com:9094
      group-id: couzy-forum-dev
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.breeze.summer.*
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer    
    producer:
      bootstrap-server: my-broker1.com:9094,my-broker2.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
flyway:
  url: jdbc:mysql://localhost:3306/couzy_forum?serverTimezone=UTC&useSSL=false
  user: root
  password: root
  ignoreMissingMigrations: true
#  locations: db/migration
server:
  port: 8083
  servlet:
    context-path: /

  
school:
  favorite-teacher:
    name: Albert Johnson
  favorite-pupil:
    name: Bob Davidson
second-server:
  url: www.second-server.com/packages/update
  apiKey: bXkgc3VwZXIgc2VjcmV0IGFwaSBrZXk=

spring.jpa.hibernate.ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error
deployment:
  env: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html # custom swagger-ui path
  api-docs:
    path: /v3/api-docs.yaml
  server:
    url: http://localhost:8080

facebook:
  topic-statistics: facebook-stats
  topic-categories: facebook-categories
